############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

# [[main]]
# name = "About"
# url = "/about"
# weight = 2

# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 2
